env: 
    seed:
                799345
    n_level:
                10  # power level count
    n_pair:
                10
    n_bs:
                1   # consant, don't change
    m_cue:
                4
    bs_power:
                10W  # W
    R_bs:
            1   # adjust to match n_t_devices
    R_dev:
            0.1
    r_bs:
            0.01
    r_dev:
            0.001
    sorter:
            recv_power
    metrics:
            - emit_power
            - recv_power
            - rate
    m_state:
            16
    rb:
            duplex
agent:
    gamma:
            0.0 # discount rate
    learning_rate:
            0.001
    init_epsilon:
            0.9
    min_epsilon:
            0.01
    batch_size:
            128